### ISSUE TITLE
Error: async/await is not yet supported in Client Components

### ISSUE THREAD

**Issue by aboutjquery** [localizely/nextjs-app-router-i18n-example#3]
When running `npm run dev`, changing the content of` lang/en.json` or `other languages`, will appear below

`Error: async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.`

I haven't changed any settings, you can reproduce the problem anytime, thanks

**Comment by lzoran** [comment]
Thank you for reporting this issue. 
This should be fixed now.
