### ISSUE TITLE
response.cookies.set('NEXT_LOCALE', nextLocale) does not work

### ISSUE THREAD

**Issue by aboutjquery** [localizely/nextjs-app-router-i18n-example#4]
Use this `nextjs-app-router-i18n-example` without changing anything

Click fr in the header to change the language, then enter `http://localhost:3000/nested1/nested2/` and it will automatically jump back to English.

How to remember the language selected by the user? thanks

**Comment by lzoran** [comment]
Hi @aboutjquery,

To use a previously selected locale stored in a cookie, an update to the middleware is required. Below is an example of how you might approach this:

The `middleware.ts` file:

```
if (pathLocale) {
  ...
} else {
  const isFirstVisit = !request.cookies.has("NEXT_LOCALE");

  const locale = isFirstVisit
    ? getLocale(request, i18n)
    : request.cookies.get("NEXT_LOCALE")?.value; // Use the locale stored in a cookie

  ...
}
```

I hope you find this solution helpful.

Moreover, you can [debug](https://nextjs.org/docs/pages/building-your-application/configuring/debugging) the middleware for a deeper understanding of the logic implemented therein.
